In [ ]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

In [ ]:
#Create a null vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
# Identity matrix
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.18393832 0.25502451 0.74124171]
  [0.6580873  0.69882604 0.45586932]
  [0.51464803 0.51491599 0.53755546]]

 [[0.04059744 0.19987979 0.74035446]
  [0.76537697 0.30797397 0.28883965]
  [0.37613598 0.24015283 0.4940209 ]]

 [[0.81827805 0.54909176 0.15971859]
  [0.71296952 0.57401022 0.03802579]
  [0.57742192 0.14621236 0.82847686]]]


In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print(Zmin, Zmax)

[[0.94248949 0.50043084 0.87804544 0.98096015 0.17401111 0.2313405
  0.04502707 0.85572965 0.19549713 0.78439618]
 [0.67709825 0.47063894 0.52309052 0.90989976 0.13838286 0.5987091
  0.35747139 0.75415561 0.44472989 0.93772123]
 [0.02238857 0.08293851 0.1703388  0.6617762  0.76658378 0.39431665
  0.32269757 0.42657065 0.71254662 0.23557445]
 [0.19495446 0.11139644 0.16102492 0.4248738  0.77599712 0.65965978
  0.93732991 0.2430608  0.777402   0.46080451]
 [0.5043004  0.21852721 0.92541323 0.0109163  0.84750363 0.94016048
  0.13207452 0.66574607 0.72979749 0.50078903]
 [0.52196395 0.619291   0.52312429 0.83701041 0.59243249 0.82347833
  0.88807875 0.6840798  0.61790447 0.59836443]
 [0.4011219  0.31271004 0.9487478  0.9565398  0.23677583 0.02922487
  0.00668468 0.28419739 0.67843349 0.50118677]
 [0.65676877 0.21712004 0.42567421 0.13826223 0.11074399 0.31102107
  0.74500445 0.74855127 0.07630425 0.64373747]
 [0.20622437 0.63958004 0.72942049 0.34053291 0.64227132 0.84747006
  0.84087042 0

In [ ]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.40087534183570966


In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
3 * 0.1 == 0.3

False

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
print(Z)
Z[::2,1::2] = 1
print(Z)


[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.29079796 0.87740625 0.70900745 0.35144638 0.76221151]
 [0.36064026 0.         0.00896051 0.22405753 0.47755427]
 [0.08675659 0.81990583 0.38737044 0.78116882 0.37423551]
 [0.46491303 0.02248129 0.40067892 1.         0.51037338]
 [0.71682382 0.52967402 0.15953206 0.64013625 0.41005443]]


In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [56]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [57]:
Z = np.random.random(10)
Z.sort()
print(Z)


[2.79174036e-04 1.08738357e-01 3.53184864e-01 3.79646066e-01
 3.86365397e-01 5.32343764e-01 5.40686038e-01 6.28530700e-01
 8.52931570e-01 8.69929710e-01]


In [59]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
equal = np.allclose(A,B)
print(equal)

[1 0 0 1 0]
[1 0 1 0 0]
False


In [60]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[0.41054632 0.15379024 0.7419032  0.91718069 0.86916801 0.68173312
 0.37855874 0.68078215 1.11945609 0.73859571]
[0.2032989  1.12476089 0.55381384 0.14905602 0.64490777 0.3424847
 0.72709141 0.36993093 0.54226604 1.50482117]


In [61]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.         0.11580594 0.42188851 0.79089371 0.41158063 0.10424704
 0.28504939 0.72269769 0.76779785 0.83161011]
